# Generated by Django 3.2.9 on 2021-11-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='Full-time', max_length=50),
            preserve_default=False,
        ),
    ]
